version: '3.8'

services:
  frontend:
    build:
      context: ../../frontend
      dockerfile: ../infrastructure/docker/frontend.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../../frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend

  backend:
    build:
      context: ../../backend
      dockerfile: ../infrastructure/docker/backend.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../../backend:/app
    environment:
      - DATABASE_URL=postgresql://catalog_user:catalog_password@postgres:5432/catalog_db
      - REDIS_URL=redis://redis:6379
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_URL=minio:9000
    depends_on:
      - postgres
      - redis
      - minio

  celery_worker:
    build:
      context: ../../backend
      dockerfile: ../infrastructure/docker/backend.Dockerfile
    command: celery -A app.worker worker --loglevel=info
    volumes:
      - ../../backend:/app
    environment:
      - DATABASE_URL=postgresql://catalog_user:catalog_password@postgres:5432/catalog_db
      - REDIS_URL=redis://redis:6379
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_URL=minio:9000
    depends_on:
      - postgres
      - redis
      - minio

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=catalog_user
      - POSTGRES_PASSWORD=catalog_password
      - POSTGRES_DB=catalog_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  postgres_data:
  minio_data:
